//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from gramatica.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="gramaticaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IgramaticaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.inicio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInicio([NotNull] gramaticaParser.InicioContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.inicio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInicio([NotNull] gramaticaParser.InicioContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PrintStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintStmt([NotNull] gramaticaParser.PrintStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PrintStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintStmt([NotNull] gramaticaParser.PrintStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprStmt([NotNull] gramaticaParser.ExprStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprStmt([NotNull] gramaticaParser.ExprStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStmt([NotNull] gramaticaParser.IfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStmt([NotNull] gramaticaParser.IfStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SwitchInstruccion</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchInstruccion([NotNull] gramaticaParser.SwitchInstruccionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SwitchInstruccion</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchInstruccion([NotNull] gramaticaParser.SwitchInstruccionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SeccionInstruccion</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeccionInstruccion([NotNull] gramaticaParser.SeccionInstruccionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SeccionInstruccion</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeccionInstruccion([NotNull] gramaticaParser.SeccionInstruccionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ForStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStmt([NotNull] gramaticaParser.ForStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ForStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStmt([NotNull] gramaticaParser.ForStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VarDeclSliceStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDeclSliceStmt([NotNull] gramaticaParser.VarDeclSliceStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VarDeclSliceStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDeclSliceStmt([NotNull] gramaticaParser.VarDeclSliceStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AsignStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsignStmt([NotNull] gramaticaParser.AsignStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AsignStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsignStmt([NotNull] gramaticaParser.AsignStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VarDeclStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDeclStmt([NotNull] gramaticaParser.VarDeclStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VarDeclStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDeclStmt([NotNull] gramaticaParser.VarDeclStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VarDeclStructStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDeclStructStmt([NotNull] gramaticaParser.VarDeclStructStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VarDeclStructStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDeclStructStmt([NotNull] gramaticaParser.VarDeclStructStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VarStructDclStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarStructDclStmt([NotNull] gramaticaParser.VarStructDclStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VarStructDclStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarStructDclStmt([NotNull] gramaticaParser.VarStructDclStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.imprimir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImprimir([NotNull] gramaticaParser.ImprimirContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.imprimir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImprimir([NotNull] gramaticaParser.ImprimirContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IfOnly</c>
	/// labeled alternative in <see cref="gramaticaParser.sIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfOnly([NotNull] gramaticaParser.IfOnlyContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IfOnly</c>
	/// labeled alternative in <see cref="gramaticaParser.sIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfOnly([NotNull] gramaticaParser.IfOnlyContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IfAnidado</c>
	/// labeled alternative in <see cref="gramaticaParser.sIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfAnidado([NotNull] gramaticaParser.IfAnidadoContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IfAnidado</c>
	/// labeled alternative in <see cref="gramaticaParser.sIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfAnidado([NotNull] gramaticaParser.IfAnidadoContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SwitchStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.sSwitch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStmt([NotNull] gramaticaParser.SwitchStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SwitchStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.sSwitch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStmt([NotNull] gramaticaParser.SwitchStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Case</c>
	/// labeled alternative in <see cref="gramaticaParser.cases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCase([NotNull] gramaticaParser.CaseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Case</c>
	/// labeled alternative in <see cref="gramaticaParser.cases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCase([NotNull] gramaticaParser.CaseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Default</c>
	/// labeled alternative in <see cref="gramaticaParser.cases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefault([NotNull] gramaticaParser.DefaultContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Default</c>
	/// labeled alternative in <see cref="gramaticaParser.cases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefault([NotNull] gramaticaParser.DefaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] gramaticaParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] gramaticaParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ForCondicion</c>
	/// labeled alternative in <see cref="gramaticaParser.sFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForCondicion([NotNull] gramaticaParser.ForCondicionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ForCondicion</c>
	/// labeled alternative in <see cref="gramaticaParser.sFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForCondicion([NotNull] gramaticaParser.ForCondicionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ForAsignacion</c>
	/// labeled alternative in <see cref="gramaticaParser.sFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForAsignacion([NotNull] gramaticaParser.ForAsignacionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ForAsignacion</c>
	/// labeled alternative in <see cref="gramaticaParser.sFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForAsignacion([NotNull] gramaticaParser.ForAsignacionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VarDclWithTypeAndValue</c>
	/// labeled alternative in <see cref="gramaticaParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDclWithTypeAndValue([NotNull] gramaticaParser.VarDclWithTypeAndValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VarDclWithTypeAndValue</c>
	/// labeled alternative in <see cref="gramaticaParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDclWithTypeAndValue([NotNull] gramaticaParser.VarDclWithTypeAndValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VarDclWithTypeOnly</c>
	/// labeled alternative in <see cref="gramaticaParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDclWithTypeOnly([NotNull] gramaticaParser.VarDclWithTypeOnlyContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VarDclWithTypeOnly</c>
	/// labeled alternative in <see cref="gramaticaParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDclWithTypeOnly([NotNull] gramaticaParser.VarDclWithTypeOnlyContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VarDclWithInference</c>
	/// labeled alternative in <see cref="gramaticaParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDclWithInference([NotNull] gramaticaParser.VarDclWithInferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VarDclWithInference</c>
	/// labeled alternative in <see cref="gramaticaParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDclWithInference([NotNull] gramaticaParser.VarDclWithInferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SliceValores</c>
	/// labeled alternative in <see cref="gramaticaParser.varDclSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSliceValores([NotNull] gramaticaParser.SliceValoresContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SliceValores</c>
	/// labeled alternative in <see cref="gramaticaParser.varDclSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSliceValores([NotNull] gramaticaParser.SliceValoresContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SliceVacio</c>
	/// labeled alternative in <see cref="gramaticaParser.varDclSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSliceVacio([NotNull] gramaticaParser.SliceVacioContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SliceVacio</c>
	/// labeled alternative in <see cref="gramaticaParser.varDclSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSliceVacio([NotNull] gramaticaParser.SliceVacioContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign([NotNull] gramaticaParser.AssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign([NotNull] gramaticaParser.AssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.nuevoSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNuevoSlice([NotNull] gramaticaParser.NuevoSliceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.nuevoSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNuevoSlice([NotNull] gramaticaParser.NuevoSliceContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SliceContenido</c>
	/// labeled alternative in <see cref="gramaticaParser.contenidoSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSliceContenido([NotNull] gramaticaParser.SliceContenidoContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SliceContenido</c>
	/// labeled alternative in <see cref="gramaticaParser.contenidoSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSliceContenido([NotNull] gramaticaParser.SliceContenidoContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SliceContenidoSlice</c>
	/// labeled alternative in <see cref="gramaticaParser.contenidoSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSliceContenidoSlice([NotNull] gramaticaParser.SliceContenidoSliceContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SliceContenidoSlice</c>
	/// labeled alternative in <see cref="gramaticaParser.contenidoSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSliceContenidoSlice([NotNull] gramaticaParser.SliceContenidoSliceContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DeclStructData</c>
	/// labeled alternative in <see cref="gramaticaParser.varDclStruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclStructData([NotNull] gramaticaParser.DeclStructDataContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DeclStructData</c>
	/// labeled alternative in <see cref="gramaticaParser.varDclStruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclStructData([NotNull] gramaticaParser.DeclStructDataContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StructVarType</c>
	/// labeled alternative in <see cref="gramaticaParser.varStructDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructVarType([NotNull] gramaticaParser.StructVarTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StructVarType</c>
	/// labeled alternative in <see cref="gramaticaParser.varStructDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructVarType([NotNull] gramaticaParser.StructVarTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>varExpr</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarExpr([NotNull] gramaticaParser.VarExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>varExpr</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarExpr([NotNull] gramaticaParser.VarExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>varAdd</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarAdd([NotNull] gramaticaParser.VarAddContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>varAdd</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarAdd([NotNull] gramaticaParser.VarAddContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>varInc</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarInc([NotNull] gramaticaParser.VarIncContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>varInc</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarInc([NotNull] gramaticaParser.VarIncContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayAccess</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayAccess([NotNull] gramaticaParser.ArrayAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayAccess</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayAccess([NotNull] gramaticaParser.ArrayAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EqualsNotEquals</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualsNotEquals([NotNull] gramaticaParser.EqualsNotEqualsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EqualsNotEquals</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualsNotEquals([NotNull] gramaticaParser.EqualsNotEqualsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddSub([NotNull] gramaticaParser.AddSubContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddSub([NotNull] gramaticaParser.AddSubContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParens([NotNull] gramaticaParser.ParensContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParens([NotNull] gramaticaParser.ParensContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayAccessSimple</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayAccessSimple([NotNull] gramaticaParser.ArrayAccessSimpleContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayAccessSimple</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayAccessSimple([NotNull] gramaticaParser.ArrayAccessSimpleContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayLength</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayLength([NotNull] gramaticaParser.ArrayLengthContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayLength</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayLength([NotNull] gramaticaParser.ArrayLengthContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Logical</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogical([NotNull] gramaticaParser.LogicalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Logical</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogical([NotNull] gramaticaParser.LogicalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] gramaticaParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] gramaticaParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDivModulo</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulDivModulo([NotNull] gramaticaParser.MulDivModuloContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDivModulo</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulDivModulo([NotNull] gramaticaParser.MulDivModuloContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Double</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDouble([NotNull] gramaticaParser.DoubleContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Double</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDouble([NotNull] gramaticaParser.DoubleContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Integer</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteger([NotNull] gramaticaParser.IntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Integer</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteger([NotNull] gramaticaParser.IntegerContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MinorMajorEqual</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMinorMajorEqual([NotNull] gramaticaParser.MinorMajorEqualContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MinorMajorEqual</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMinorMajorEqual([NotNull] gramaticaParser.MinorMajorEqualContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNot([NotNull] gramaticaParser.NotContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNot([NotNull] gramaticaParser.NotContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] gramaticaParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] gramaticaParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Char</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChar([NotNull] gramaticaParser.CharContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Char</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChar([NotNull] gramaticaParser.CharContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Negate</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegate([NotNull] gramaticaParser.NegateContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Negate</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegate([NotNull] gramaticaParser.NegateContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Boolean</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean([NotNull] gramaticaParser.BooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Boolean</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean([NotNull] gramaticaParser.BooleanContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayJoin</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayJoin([NotNull] gramaticaParser.ArrayJoinContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayJoin</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayJoin([NotNull] gramaticaParser.ArrayJoinContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayFindIndex</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayFindIndex([NotNull] gramaticaParser.ArrayFindIndexContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayFindIndex</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayFindIndex([NotNull] gramaticaParser.ArrayFindIndexContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayAppend</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayAppend([NotNull] gramaticaParser.ArrayAppendContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayAppend</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayAppend([NotNull] gramaticaParser.ArrayAppendContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] gramaticaParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] gramaticaParser.TypeContext context);
}
