//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from gramatica.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IgramaticaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class gramaticaBaseListener : IgramaticaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.inicio"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInicio([NotNull] gramaticaParser.InicioContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.inicio"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInicio([NotNull] gramaticaParser.InicioContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PrintStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintStmt([NotNull] gramaticaParser.PrintStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrintStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintStmt([NotNull] gramaticaParser.PrintStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStmt([NotNull] gramaticaParser.IfStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStmt([NotNull] gramaticaParser.IfStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SwitchInstruccion</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchInstruccion([NotNull] gramaticaParser.SwitchInstruccionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SwitchInstruccion</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchInstruccion([NotNull] gramaticaParser.SwitchInstruccionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SeccionInstruccion</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeccionInstruccion([NotNull] gramaticaParser.SeccionInstruccionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SeccionInstruccion</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeccionInstruccion([NotNull] gramaticaParser.SeccionInstruccionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ForStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStmt([NotNull] gramaticaParser.ForStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ForStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStmt([NotNull] gramaticaParser.ForStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VarDeclSliceStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDeclSliceStmt([NotNull] gramaticaParser.VarDeclSliceStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VarDeclSliceStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDeclSliceStmt([NotNull] gramaticaParser.VarDeclSliceStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AsignStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsignStmt([NotNull] gramaticaParser.AsignStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AsignStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsignStmt([NotNull] gramaticaParser.AsignStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VarDeclStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDeclStmt([NotNull] gramaticaParser.VarDeclStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VarDeclStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDeclStmt([NotNull] gramaticaParser.VarDeclStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VarDeclStructStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDeclStructStmt([NotNull] gramaticaParser.VarDeclStructStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VarDeclStructStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDeclStructStmt([NotNull] gramaticaParser.VarDeclStructStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VarStructDclStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarStructDclStmt([NotNull] gramaticaParser.VarStructDclStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VarStructDclStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarStructDclStmt([NotNull] gramaticaParser.VarStructDclStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BreakStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStmt([NotNull] gramaticaParser.BreakStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BreakStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStmt([NotNull] gramaticaParser.BreakStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ContinueStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStmt([NotNull] gramaticaParser.ContinueStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ContinueStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStmt([NotNull] gramaticaParser.ContinueStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FunctionStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionStmt([NotNull] gramaticaParser.FunctionStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FunctionStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionStmt([NotNull] gramaticaParser.FunctionStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>CallFunctionStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallFunctionStmt([NotNull] gramaticaParser.CallFunctionStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CallFunctionStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallFunctionStmt([NotNull] gramaticaParser.CallFunctionStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ReturnStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStmt([NotNull] gramaticaParser.ReturnStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ReturnStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStmt([NotNull] gramaticaParser.ReturnStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.imprimir"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImprimir([NotNull] gramaticaParser.ImprimirContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.imprimir"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImprimir([NotNull] gramaticaParser.ImprimirContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IfOnly</c>
	/// labeled alternative in <see cref="gramaticaParser.sIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfOnly([NotNull] gramaticaParser.IfOnlyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IfOnly</c>
	/// labeled alternative in <see cref="gramaticaParser.sIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfOnly([NotNull] gramaticaParser.IfOnlyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IfAnidado</c>
	/// labeled alternative in <see cref="gramaticaParser.sIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfAnidado([NotNull] gramaticaParser.IfAnidadoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IfAnidado</c>
	/// labeled alternative in <see cref="gramaticaParser.sIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfAnidado([NotNull] gramaticaParser.IfAnidadoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SwitchStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.sSwitch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStmt([NotNull] gramaticaParser.SwitchStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SwitchStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.sSwitch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStmt([NotNull] gramaticaParser.SwitchStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Case</c>
	/// labeled alternative in <see cref="gramaticaParser.cases"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCase([NotNull] gramaticaParser.CaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Case</c>
	/// labeled alternative in <see cref="gramaticaParser.cases"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCase([NotNull] gramaticaParser.CaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Default</c>
	/// labeled alternative in <see cref="gramaticaParser.cases"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefault([NotNull] gramaticaParser.DefaultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Default</c>
	/// labeled alternative in <see cref="gramaticaParser.cases"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefault([NotNull] gramaticaParser.DefaultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>blockStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockStmt([NotNull] gramaticaParser.BlockStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>blockStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockStmt([NotNull] gramaticaParser.BlockStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ForCondicion</c>
	/// labeled alternative in <see cref="gramaticaParser.sFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForCondicion([NotNull] gramaticaParser.ForCondicionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ForCondicion</c>
	/// labeled alternative in <see cref="gramaticaParser.sFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForCondicion([NotNull] gramaticaParser.ForCondicionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ForAsignacion</c>
	/// labeled alternative in <see cref="gramaticaParser.sFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForAsignacion([NotNull] gramaticaParser.ForAsignacionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ForAsignacion</c>
	/// labeled alternative in <see cref="gramaticaParser.sFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForAsignacion([NotNull] gramaticaParser.ForAsignacionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ForRange</c>
	/// labeled alternative in <see cref="gramaticaParser.sFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForRange([NotNull] gramaticaParser.ForRangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ForRange</c>
	/// labeled alternative in <see cref="gramaticaParser.sFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForRange([NotNull] gramaticaParser.ForRangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VarDclWithTypeAndValue</c>
	/// labeled alternative in <see cref="gramaticaParser.varDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDclWithTypeAndValue([NotNull] gramaticaParser.VarDclWithTypeAndValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VarDclWithTypeAndValue</c>
	/// labeled alternative in <see cref="gramaticaParser.varDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDclWithTypeAndValue([NotNull] gramaticaParser.VarDclWithTypeAndValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VarDclWithTypeOnly</c>
	/// labeled alternative in <see cref="gramaticaParser.varDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDclWithTypeOnly([NotNull] gramaticaParser.VarDclWithTypeOnlyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VarDclWithTypeOnly</c>
	/// labeled alternative in <see cref="gramaticaParser.varDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDclWithTypeOnly([NotNull] gramaticaParser.VarDclWithTypeOnlyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VarDclWithInference</c>
	/// labeled alternative in <see cref="gramaticaParser.varDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDclWithInference([NotNull] gramaticaParser.VarDclWithInferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VarDclWithInference</c>
	/// labeled alternative in <see cref="gramaticaParser.varDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDclWithInference([NotNull] gramaticaParser.VarDclWithInferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SliceValores</c>
	/// labeled alternative in <see cref="gramaticaParser.varDclSlice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSliceValores([NotNull] gramaticaParser.SliceValoresContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SliceValores</c>
	/// labeled alternative in <see cref="gramaticaParser.varDclSlice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSliceValores([NotNull] gramaticaParser.SliceValoresContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SliceVacio</c>
	/// labeled alternative in <see cref="gramaticaParser.varDclSlice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSliceVacio([NotNull] gramaticaParser.SliceVacioContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SliceVacio</c>
	/// labeled alternative in <see cref="gramaticaParser.varDclSlice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSliceVacio([NotNull] gramaticaParser.SliceVacioContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssign([NotNull] gramaticaParser.AssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssign([NotNull] gramaticaParser.AssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.nuevoSlice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNuevoSlice([NotNull] gramaticaParser.NuevoSliceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.nuevoSlice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNuevoSlice([NotNull] gramaticaParser.NuevoSliceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SliceContenido</c>
	/// labeled alternative in <see cref="gramaticaParser.contenidoSlice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSliceContenido([NotNull] gramaticaParser.SliceContenidoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SliceContenido</c>
	/// labeled alternative in <see cref="gramaticaParser.contenidoSlice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSliceContenido([NotNull] gramaticaParser.SliceContenidoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SliceContenidoSlice</c>
	/// labeled alternative in <see cref="gramaticaParser.contenidoSlice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSliceContenidoSlice([NotNull] gramaticaParser.SliceContenidoSliceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SliceContenidoSlice</c>
	/// labeled alternative in <see cref="gramaticaParser.contenidoSlice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSliceContenidoSlice([NotNull] gramaticaParser.SliceContenidoSliceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DeclStructData</c>
	/// labeled alternative in <see cref="gramaticaParser.varDclStruct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclStructData([NotNull] gramaticaParser.DeclStructDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DeclStructData</c>
	/// labeled alternative in <see cref="gramaticaParser.varDclStruct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclStructData([NotNull] gramaticaParser.DeclStructDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StructVarType</c>
	/// labeled alternative in <see cref="gramaticaParser.varStructDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructVarType([NotNull] gramaticaParser.StructVarTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StructVarType</c>
	/// labeled alternative in <see cref="gramaticaParser.varStructDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructVarType([NotNull] gramaticaParser.StructVarTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StructVarTypeInference</c>
	/// labeled alternative in <see cref="gramaticaParser.varStructDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructVarTypeInference([NotNull] gramaticaParser.StructVarTypeInferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StructVarTypeInference</c>
	/// labeled alternative in <see cref="gramaticaParser.varStructDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructVarTypeInference([NotNull] gramaticaParser.StructVarTypeInferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>varExpr</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarExpr([NotNull] gramaticaParser.VarExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>varExpr</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarExpr([NotNull] gramaticaParser.VarExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>varAdd</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarAdd([NotNull] gramaticaParser.VarAddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>varAdd</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarAdd([NotNull] gramaticaParser.VarAddContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>varInc</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarInc([NotNull] gramaticaParser.VarIncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>varInc</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarInc([NotNull] gramaticaParser.VarIncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayAccess</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAccess([NotNull] gramaticaParser.ArrayAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayAccess</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAccess([NotNull] gramaticaParser.ArrayAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StructAccessAsign</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructAccessAsign([NotNull] gramaticaParser.StructAccessAsignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StructAccessAsign</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructAccessAsign([NotNull] gramaticaParser.StructAccessAsignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParens([NotNull] gramaticaParser.ParensContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParens([NotNull] gramaticaParser.ParensContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>CallFunctionValue</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallFunctionValue([NotNull] gramaticaParser.CallFunctionValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CallFunctionValue</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallFunctionValue([NotNull] gramaticaParser.CallFunctionValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Logical</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogical([NotNull] gramaticaParser.LogicalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Logical</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogical([NotNull] gramaticaParser.LogicalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] gramaticaParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] gramaticaParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StructAccess</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructAccess([NotNull] gramaticaParser.StructAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StructAccess</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructAccess([NotNull] gramaticaParser.StructAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] gramaticaParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] gramaticaParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Char</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChar([NotNull] gramaticaParser.CharContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Char</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChar([NotNull] gramaticaParser.CharContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Boolean</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean([NotNull] gramaticaParser.BooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Boolean</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean([NotNull] gramaticaParser.BooleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayFindIndex</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayFindIndex([NotNull] gramaticaParser.ArrayFindIndexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayFindIndex</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayFindIndex([NotNull] gramaticaParser.ArrayFindIndexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayAppend</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAppend([NotNull] gramaticaParser.ArrayAppendContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayAppend</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAppend([NotNull] gramaticaParser.ArrayAppendContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EqualsNotEquals</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualsNotEquals([NotNull] gramaticaParser.EqualsNotEqualsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EqualsNotEquals</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualsNotEquals([NotNull] gramaticaParser.EqualsNotEqualsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IntToString</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntToString([NotNull] gramaticaParser.IntToStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IntToString</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntToString([NotNull] gramaticaParser.IntToStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddSub([NotNull] gramaticaParser.AddSubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddSub([NotNull] gramaticaParser.AddSubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayAccessSimple</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAccessSimple([NotNull] gramaticaParser.ArrayAccessSimpleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayAccessSimple</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAccessSimple([NotNull] gramaticaParser.ArrayAccessSimpleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayLength</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayLength([NotNull] gramaticaParser.ArrayLengthContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayLength</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayLength([NotNull] gramaticaParser.ArrayLengthContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDivModulo</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulDivModulo([NotNull] gramaticaParser.MulDivModuloContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDivModulo</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulDivModulo([NotNull] gramaticaParser.MulDivModuloContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Double</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDouble([NotNull] gramaticaParser.DoubleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Double</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDouble([NotNull] gramaticaParser.DoubleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Integer</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger([NotNull] gramaticaParser.IntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Integer</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger([NotNull] gramaticaParser.IntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Nil</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNil([NotNull] gramaticaParser.NilContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Nil</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNil([NotNull] gramaticaParser.NilContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MinorMajorEqual</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMinorMajorEqual([NotNull] gramaticaParser.MinorMajorEqualContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MinorMajorEqual</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMinorMajorEqual([NotNull] gramaticaParser.MinorMajorEqualContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNot([NotNull] gramaticaParser.NotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNot([NotNull] gramaticaParser.NotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>reflectType</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReflectType([NotNull] gramaticaParser.ReflectTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>reflectType</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReflectType([NotNull] gramaticaParser.ReflectTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Negate</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegate([NotNull] gramaticaParser.NegateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Negate</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegate([NotNull] gramaticaParser.NegateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayJoin</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayJoin([NotNull] gramaticaParser.ArrayJoinContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayJoin</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayJoin([NotNull] gramaticaParser.ArrayJoinContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>floatToString</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatToString([NotNull] gramaticaParser.FloatToStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>floatToString</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatToString([NotNull] gramaticaParser.FloatToStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.posicion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPosicion([NotNull] gramaticaParser.PosicionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.posicion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPosicion([NotNull] gramaticaParser.PosicionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] gramaticaParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] gramaticaParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.break"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreak([NotNull] gramaticaParser.BreakContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.break"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreak([NotNull] gramaticaParser.BreakContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.continue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinue([NotNull] gramaticaParser.ContinueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.continue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinue([NotNull] gramaticaParser.ContinueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Funciones</c>
	/// labeled alternative in <see cref="gramaticaParser.functions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunciones([NotNull] gramaticaParser.FuncionesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Funciones</c>
	/// labeled alternative in <see cref="gramaticaParser.functions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunciones([NotNull] gramaticaParser.FuncionesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>CallFunction</c>
	/// labeled alternative in <see cref="gramaticaParser.varCallStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallFunction([NotNull] gramaticaParser.CallFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CallFunction</c>
	/// labeled alternative in <see cref="gramaticaParser.varCallStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallFunction([NotNull] gramaticaParser.CallFunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.valRet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValRet([NotNull] gramaticaParser.ValRetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.valRet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValRet([NotNull] gramaticaParser.ValRetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.retorno"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetorno([NotNull] gramaticaParser.RetornoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.retorno"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetorno([NotNull] gramaticaParser.RetornoContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
