//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from gramatica.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="gramaticaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IgramaticaVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.inicio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInicio([NotNull] gramaticaParser.InicioContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PrintStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStmt([NotNull] gramaticaParser.PrintStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExprStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprStmt([NotNull] gramaticaParser.ExprStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStmt([NotNull] gramaticaParser.IfStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SwitchInstruccion</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchInstruccion([NotNull] gramaticaParser.SwitchInstruccionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SeccionInstruccion</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeccionInstruccion([NotNull] gramaticaParser.SeccionInstruccionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ForStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStmt([NotNull] gramaticaParser.ForStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VarDeclSliceStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDeclSliceStmt([NotNull] gramaticaParser.VarDeclSliceStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AsignStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignStmt([NotNull] gramaticaParser.AsignStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VarDeclStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDeclStmt([NotNull] gramaticaParser.VarDeclStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.imprimir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImprimir([NotNull] gramaticaParser.ImprimirContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfOnly</c>
	/// labeled alternative in <see cref="gramaticaParser.sIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfOnly([NotNull] gramaticaParser.IfOnlyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfAnidado</c>
	/// labeled alternative in <see cref="gramaticaParser.sIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfAnidado([NotNull] gramaticaParser.IfAnidadoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SwitchStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.sSwitch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStmt([NotNull] gramaticaParser.SwitchStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Case</c>
	/// labeled alternative in <see cref="gramaticaParser.cases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase([NotNull] gramaticaParser.CaseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Default</c>
	/// labeled alternative in <see cref="gramaticaParser.cases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefault([NotNull] gramaticaParser.DefaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] gramaticaParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ForCondicion</c>
	/// labeled alternative in <see cref="gramaticaParser.sFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForCondicion([NotNull] gramaticaParser.ForCondicionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ForAsignacion</c>
	/// labeled alternative in <see cref="gramaticaParser.sFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForAsignacion([NotNull] gramaticaParser.ForAsignacionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VarDclWithTypeAndValue</c>
	/// labeled alternative in <see cref="gramaticaParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDclWithTypeAndValue([NotNull] gramaticaParser.VarDclWithTypeAndValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VarDclWithTypeOnly</c>
	/// labeled alternative in <see cref="gramaticaParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDclWithTypeOnly([NotNull] gramaticaParser.VarDclWithTypeOnlyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VarDclWithInference</c>
	/// labeled alternative in <see cref="gramaticaParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDclWithInference([NotNull] gramaticaParser.VarDclWithInferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SliceValores</c>
	/// labeled alternative in <see cref="gramaticaParser.varDclSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSliceValores([NotNull] gramaticaParser.SliceValoresContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SliceVacio</c>
	/// labeled alternative in <see cref="gramaticaParser.varDclSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSliceVacio([NotNull] gramaticaParser.SliceVacioContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign([NotNull] gramaticaParser.AssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varExpr</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarExpr([NotNull] gramaticaParser.VarExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varAdd</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarAdd([NotNull] gramaticaParser.VarAddContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varInc</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarInc([NotNull] gramaticaParser.VarIncContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayAccess</c>
	/// labeled alternative in <see cref="gramaticaParser.varAsign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccess([NotNull] gramaticaParser.ArrayAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EqualsNotEquals</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualsNotEquals([NotNull] gramaticaParser.EqualsNotEqualsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddSub([NotNull] gramaticaParser.AddSubContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParens([NotNull] gramaticaParser.ParensContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayAccessSimple</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccessSimple([NotNull] gramaticaParser.ArrayAccessSimpleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayLength</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayLength([NotNull] gramaticaParser.ArrayLengthContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Logical</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical([NotNull] gramaticaParser.LogicalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] gramaticaParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MulDivModulo</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulDivModulo([NotNull] gramaticaParser.MulDivModuloContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Double</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDouble([NotNull] gramaticaParser.DoubleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Integer</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteger([NotNull] gramaticaParser.IntegerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MinorMajorEqual</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMinorMajorEqual([NotNull] gramaticaParser.MinorMajorEqualContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot([NotNull] gramaticaParser.NotContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] gramaticaParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Char</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChar([NotNull] gramaticaParser.CharContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Negate</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegate([NotNull] gramaticaParser.NegateContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Boolean</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean([NotNull] gramaticaParser.BooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayJoin</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayJoin([NotNull] gramaticaParser.ArrayJoinContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayFindIndex</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayFindIndex([NotNull] gramaticaParser.ArrayFindIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayAppend</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAppend([NotNull] gramaticaParser.ArrayAppendContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] gramaticaParser.TypeContext context);
}
